name: linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry update

      - name: Run flake8 linter
        run: make lint
